apiVersion: apps/v1
kind: Deployment
metadata:
  name: pomo-timer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pomo-timer
  template:
    metadata:
      labels:
        app: pomo-timer
    spec:
      containers:
      - name: pomo-timer
        image: gcr.io/gcp-demo-project-487205/pomo-timer:f7a1b82d60636b40a0603be510edf2957d03c338
        ports:
        - containerPort: 80
