apiVersion: v1
kind: Service
metadata:
  name: pomo-timer
  namespace: default
  labels:
    app: pomo-timer
spec:
  type: LoadBalancer
  selector:
    app: pomo-timer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
